baseURL          = "https://lingua-pupuli.github.io/"
title            = "Puppet VSCode Extension"
languageCode     = "en-us"
sectionPagesMenu = "main"

[params]
  subtitle     = "An open-source extension for Visual Studio Code"
  extensionURL = '//pup.pt/vscode'
  github       = '//github.com/lingua-pupuli/puppet-vscode'
  twitter      = '//twitter.com/puppetize'
  slack        = '//puppetcommunity.slack.com'
  youtube      = '//www.youtube.com/results?search_query=%23PuppetizeLive'
  email        = '//puppetcommunity.slack.com'
